# This is a basic workflow to help you get started with Actions

name: Jobs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:
    - master
  schedule:
    - cron: "0 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  call:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Jobs trigger
        # Being pushed and pull request merged may contain site related changes, just rebuild the site always
        run: |
          while IFS= read -r repo ; do \
          &>/dev/null curl -X POST -Ss https://api.github.com/repos/${{ github.actor }}/$repo/actions/workflows/dispatch.yml/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -H 'Authorization: token ${{ secrets.PAT }}' \
          --data '{"ref": "dispatch"}' \
          ; done <<< "${{ secrets.REPO }}"
      - name: Log
        run: |
          echo $(date +%d.%m.%Y) > run.log
      - name: Commit files
        id: commit
        run: |
          git config --local user.email "action@users.noreply.github.com"
          git config --local user.name "Github Action Bot"
          git add .
          &>/dev/null git commit -m "Last active: $(date +%d.%m.%Y)" && echo "::set-output name=committed::1" || echo "Nothing to update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}